import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='p-10'>
      <body className={inter.className}>
        <nav>
          <ul className='flex gap-6 text-green-600 font-semibold'>
            <li>
              <Link href={"/"}>Home</Link>
            </li>
            <li>
              <Link href={"/about"}>about</Link>
            </li>

          </ul>
        </nav>
        {children}
        </body>
    </html>
  )
}
